sudo: required

services: 
  - docker

before_install:
  - docker build -t rnaydenov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rnaydenov/docker-react npm run test -- --coverage